// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnUXAiK9OxjfLtN_5YSBYtOglmFgfGXk0',
    appId: '1:92714869815:web:7db475939559f69bec8bb2',
    messagingSenderId: '92714869815',
    projectId: 'crud-69580',
    authDomain: 'crud-69580.firebaseapp.com',
    storageBucket: 'crud-69580.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp382RjxyQ6o3RqELv3KPIvoT9dkOP2zM',
    appId: '1:92714869815:android:20ab9bfc411d98d6ec8bb2',
    messagingSenderId: '92714869815',
    projectId: 'crud-69580',
    storageBucket: 'crud-69580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFC3WrwlEofEg2mSTCoBm1RJqNJFWnpzE',
    appId: '1:92714869815:ios:fbca75e607267360ec8bb2',
    messagingSenderId: '92714869815',
    projectId: 'crud-69580',
    storageBucket: 'crud-69580.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFC3WrwlEofEg2mSTCoBm1RJqNJFWnpzE',
    appId: '1:92714869815:ios:fbca75e607267360ec8bb2',
    messagingSenderId: '92714869815',
    projectId: 'crud-69580',
    storageBucket: 'crud-69580.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnUXAiK9OxjfLtN_5YSBYtOglmFgfGXk0',
    appId: '1:92714869815:web:c9a563849166aae0ec8bb2',
    messagingSenderId: '92714869815',
    projectId: 'crud-69580',
    authDomain: 'crud-69580.firebaseapp.com',
    storageBucket: 'crud-69580.appspot.com',
  );
}
